# Generated by Django 5.2.3 on 2025-06-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlisting',
            name='classification',
            field=models.CharField(blank=True, help_text='NIST SP 800-60 information impact level with value (e.g., "High (0.85)")', max_length=255, null=True),
        ),
    ]
