# Generated by Django 5.2.3 on 2025-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0002_update_classification_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='business_criticality',
            field=models.FloatField(default=0.5, help_text='Business criticality level (0-1 scale): How critical is this department to core business operations'),
        ),
        migrations.AddField(
            model_name='department',
            name='data_sensitivity',
            field=models.FloatField(default=0.5, help_text='Data sensitivity level (0-1 scale): Sensitivity of data typically handled by this department'),
        ),
        migrations.AddField(
            model_name='department',
            name='operational_dependency',
            field=models.FloatField(default=0.5, help_text='Operational dependency level (0-1 scale): How much other departments depend on this department'),
        ),
        migrations.AddField(
            model_name='department',
            name='regulatory_impact',
            field=models.FloatField(default=0.5, help_text='Regulatory impact level (0-1 scale): Level of regulatory oversight and compliance requirements'),
        ),
    ]
