# Generated by Django 5.2.3 on 2025-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0003_add_organizational_impact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='business_criticality',
        ),
        migrations.RemoveField(
            model_name='department',
            name='data_sensitivity',
        ),
        migrations.RemoveField(
            model_name='department',
            name='operational_dependency',
        ),
        migrations.RemoveField(
            model_name='department',
            name='regulatory_impact',
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='business_criticality',
            field=models.FloatField(blank=True, help_text='Business criticality level (0-1 scale): How critical is this asset to core business operations', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='data_sensitivity',
            field=models.FloatField(blank=True, help_text='Data sensitivity level (0-1 scale): Sensitivity of data handled/stored by this asset', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='operational_dependency',
            field=models.FloatField(blank=True, help_text='Operational dependency level (0-1 scale): How much other systems/processes depend on this asset', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='regulatory_impact',
            field=models.FloatField(blank=True, help_text='Regulatory impact level (0-1 scale): Level of regulatory oversight for this specific asset', null=True),
        ),
    ]
