# Generated by Django 5.2.3 on 2025-06-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0004_remove_dept_impact_add_asset_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlisting',
            name='asset_value',
        ),
    ]
