# Generated by Django 5.2.3 on 2025-06-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0005_remove_asset_value_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='asset_value_mapping',
        ),
    ]
