# Generated by Django 5.2.3 on 2025-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0006_remove_department_asset_value_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetValueMapping',
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='modern_dt_prediction',
            field=models.CharField(blank=True, choices=[('Low Impact', 'Low Impact'), ('Moderate Impact', 'Moderate Impact'), ('High Impact', 'High Impact')], help_text='Modern Decision Tree classification prediction (NIST SP 800-60)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='modern_svm_prediction',
            field=models.CharField(blank=True, choices=[('Low Impact', 'Low Impact'), ('Moderate Impact', 'Moderate Impact'), ('High Impact', 'High Impact')], help_text='Modern SVM classification prediction (NIST SP 800-60)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='traditional_fuzzy_prediction',
            field=models.CharField(blank=True, choices=[('Low Impact', 'Low Impact'), ('Moderate Impact', 'Moderate Impact'), ('High Impact', 'High Impact')], help_text='Traditional fuzzy logic classification prediction (NIST SP 800-60)', max_length=20, null=True),
        ),
    ]
