# Generated by Django 5.2.3 on 2025-06-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0007_update_classification_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlisting',
            name='modern_dt_prediction',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Official', 'Official'), ('Confidential', 'Confidential'), ('Restricted', 'Restricted')], help_text='Modern Decision Tree classification prediction (Government Classification)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='modern_svm_prediction',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Official', 'Official'), ('Confidential', 'Confidential'), ('Restricted', 'Restricted')], help_text='Modern SVM classification prediction (Government Classification)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='traditional_fuzzy_prediction',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Official', 'Official'), ('Confidential', 'Confidential'), ('Restricted', 'Restricted')], help_text='Traditional fuzzy logic classification prediction (Government Classification)', max_length=20, null=True),
        ),
    ]
