# Generated by Django 5.2.3 on 2025-06-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0008_update_classification_to_government_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlisting',
            name='modern_dt_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for modern Decision Tree prediction (0-1 scale)', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='modern_svm_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for modern SVM prediction (0-1 scale)', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='traditional_fuzzy_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for traditional fuzzy logic prediction (0-1 scale)', null=True),
        ),
    ]
