# Generated by Django 5.2.3 on 2025-06-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0009_assetlisting_modern_dt_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlisting',
            name='modern_dt_score',
            field=models.FloatField(blank=True, help_text='Classification score for modern Decision Tree prediction (0-1 scale)', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='modern_svm_score',
            field=models.FloatField(blank=True, help_text='Classification score for modern SVM prediction (0-1 scale)', null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='traditional_fuzzy_score',
            field=models.FloatField(blank=True, help_text='Classification score for traditional fuzzy logic prediction (0-1 scale)', null=True),
        ),
    ]
