# Generated by Django 5.2.3 on 2025-06-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0010_assetlisting_modern_dt_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlisting',
            name='modern_dt_confidence',
        ),
        migrations.RemoveField(
            model_name='assetlisting',
            name='modern_svm_confidence',
        ),
        migrations.RemoveField(
            model_name='assetlisting',
            name='traditional_fuzzy_confidence',
        ),
        migrations.RemoveField(
            model_name='modelcomparison',
            name='dt_confidence',
        ),
        migrations.RemoveField(
            model_name='modelcomparison',
            name='fuzzy_confidence',
        ),
        migrations.RemoveField(
            model_name='modelcomparison',
            name='svm_confidence',
        ),
    ]
